inherit_from: https://raw.githubusercontent.com/halo/dotfiles/master/dotfiles/rubocop.yml
#inherit_from: ~/.rubocop.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - 'Vendor/bundle/**/*'
  SuggestExtensions: false
