sudo: required
language: swift
rvm: 2.6.3

matrix:
  include:
    - osx_image: xcode11.2

before_script:
  - bundle install
  - sudo gem install bundler --no-document
  - sudo bundle install

script:
  - bundle exec rake
  - bundle exec rspec --tag ~sudo
  - sudo bundle exec rspec --tag sudo
  - bundle exec rubocop
